import { GameFactory } from "../factories/GameFactory.js";
import { MESSAGES } from "../messages.js";

// prettier-ignore
export const LEVELS = {
    1: () => {
        return {
            worldSize: {
                width: GameFactory.GRID * 192,
                height: GameFactory.GRID * 112,
            },
            playerStart: {
                x: GameFactory.GRID * 2,
                y: GameFactory.GRID * 86,
            },
            platforms: [
                // GROUND
                GameFactory.grid.solid({ id: 1, x: 0, y: 110, w: 192, h: 4 }),
                //CEIL
                GameFactory.grid.solid({ id: 2, x: 0, y: -2, w: 192, h: 6 }),

                GameFactory.grid.booster({ id: 3, x: 0, y: 60, w: 3, h: 1, boostSpeed: 29 }),
                GameFactory.grid.solid({ id: 4, x: 1, y: 21, w: 2, h: 20 }),
                GameFactory.grid.booster({ id: 5, x: 3, y: 47, w: 5, h: 1, boostSpeed: 38 }),
                GameFactory.grid.solid({ id: 6, x: 6, y: 17, w: 2, h: 1, layout: "boardLeftCap" }),
                GameFactory.grid.solid({ id: 7, x: 8, y: 12, w: 2, h: 15 }),
                GameFactory.grid.solid({ id: 8, x: 9, y: 107.5, w: 5, h: 1, layout: "board" }),
                GameFactory.grid.solid({ id: 9, x: 10, y: 13, w: 2, h: 1, layout: "boardRightCap" }),
                GameFactory.grid.solid({ id: 10, x: 11, y: 47, w: 6, h: 1, layout: "board" }),
                GameFactory.grid.solid({ id: 11, x: 17, y: 104, w: 12, h: 1, layout: "board" }),
                GameFactory.grid.solid({ id: 12, x: 18, y: 11, w: 40, h: 6 }),
                GameFactory.grid.solid({ id: 13, x: 18, y: 52, w: 2, h: 1, layout: "board" }),
                GameFactory.grid.solid({ id: 14, x: 15, y: 66, w: 7, h: 1, layout: "board" }),
                GameFactory.grid.solid({ id: 15, x: 23, y: 61, w: 2, h: 1, layout: "board" }),
                GameFactory.grid.solid({ id: 16, x: 25, y: 10, w: 2, h: 2, layout: "metal" }),
                GameFactory.grid.solid({ id: 17, x: 25, y: 56, w: 2, h: 1, layout: "board" }),
                GameFactory.grid.solid({ id: 18, x: 26, y: 70, w: 5, h: 1, layout: "board" }),
                GameFactory.grid.solid({ id: 19, x: 31, y: 102, w: 2, h: 1, layout: "board" }),
                GameFactory.grid.solid({ id: 20, x: 36, y: 98, w: 10, h: 6 }),
                GameFactory.grid.solid({ id: 21, x: 35, y: 72, w: 8, h: 4 }),
                GameFactory.grid.solid({ id: 22, x: 45, y: 9, w: 2, h: 2, layout: "metal" }),
                GameFactory.grid.solid({ id: 23, x: 48, y: 74, w: 14, h: 1, layout: "board" }),
                GameFactory.grid.solid({ id: 24, x: 48, y: 78, w: 14, h: 2 }),
                GameFactory.grid.solid({ id: 25, x: 46, y: 102, w: 2, h: 1, layout: "boardRightCap" }),
                GameFactory.grid.solid({ id: 26, x: 52, y: 95, w: 12, h: 3 }),
                GameFactory.grid.booster({ id: 27, x: 55, y: 109, w: 6, h: 1 }),
                GameFactory.grid.solid({ id: 28, x: 58, y: 12, w: 4, h: 1, layout: "boardRightCap" }),
                GameFactory.grid.solid({ id: 29, x: 63, y: 14, w: 4, h: 1, layout: "board" }),
                GameFactory.grid.solid({ id: 30, x: 63, y: 91, w: 2, h: 1, layout: "board" }),
                GameFactory.grid.solid({ id: 31, x: 66, y: 105, w: 6, h: 6, layout: "groundTopCap" }),
                GameFactory.grid.booster({ id: 32, x: 67, y: 87, w: 8, h: 1, boostSpeed: 30 }),
                GameFactory.grid.solid({ id: 33, x: 67, y: 96, w: 4, h: 1, layout: "board" }),
                GameFactory.grid.solid({ id: 34, x: 68, y: 16, w: 4, h: 1, layout: "board" }),
                GameFactory.grid.solid({ id: 35, x: 72, y: 23, w: 2, h: 1, layout: "boardLeftCap" }),
                GameFactory.grid.solid({ id: 36, x: 74, y: 18, w: 2, h: 30 }),
                GameFactory.grid.solid({ id: 37, x: 74, y: 70, w: 10, h: 4 }),
                GameFactory.grid.solid({ id: 38, x: 74, y: 101, w: 2, h: 1, layout: "board" }),
                GameFactory.grid.booster({ id: 39, x: 76, y: 52, w: 5, h: 1, boostSpeed: 44 }),
                GameFactory.grid.solid({ id: 40, x: 79, y: 99, w: 12, h: 1, layout: "board" }),
                GameFactory.grid.solid({ id: 41, x: 81, y: 18, w: 2, h: 30 }),
                GameFactory.grid.solid({ id: 42, x: 83, y: 24, w: 3, h: 1, layout: "boardConnector" }),
                GameFactory.grid.solid({ id: 43, x: 86, y: 20, w: 30, h: 1, layout: "board" }),
                GameFactory.grid.solid({ id: 44, x: 86, y: 21, w: 30, h: 5 }),
                GameFactory.grid.solid({ id: 45, x: 90, y: 74, w: 6, h: 1, layout: "board" }),
                GameFactory.grid.solid({ id: 46, x: 93, y: 108, w: 6, h: 2, layout: "metal" }),
                GameFactory.grid.booster({ id: 47, x: 101, y: 77, w: 5, h: 1, boostSpeed: 42 }),
                GameFactory.grid.solid({ id: 48, x: 101, y: 78, w: 5, h: 22 }),
                GameFactory.grid.solid({ id: 49, x: 106, y: 45, w: 9, h: 1, layout: "board" }),
                GameFactory.grid.solid({ id: 50, x: 110, y: 106.5, w: 30, h: 2 }),
                GameFactory.grid.booster({ id: 51, x: 114, y: 83, w: 3, h: 1, boostSpeed: 30 }),
                GameFactory.grid.solid({ id: 52, x: 116, y: 24, w: 2, h: 1, layout: "boardRightCap" }),
                GameFactory.grid.booster({ id: 53, x: 118, y: 43, w: 8, h: 1, boostSpeed: 32 }),
                GameFactory.grid.solid({ id: 54, x: 120, y: 68, w: 10, h: 2 }),
                GameFactory.grid.solid({ id: 55, x: 121, y: 86, w: 5, h: 1, layout: "board" }),
                GameFactory.grid.solid({ id: 56, x: 122, y: 18, w: 18, h: 1, layout: "boardLeftCap" }),
                GameFactory.grid.solid({ id: 57, x: 128, y: 47, w: 2, h: 1, layout: "board" }),
                GameFactory.grid.solid({ id: 58, x: 130, y: 51, w: 5, h: 1, layout: "board" }),
                GameFactory.grid.solid({ id: 59, x: 130, y: 90, w: 12, h: 1, layout: "board" }),
                GameFactory.grid.solid({ id: 60, x: 134, y: 65, w: 2, h: 1, layout: "board" }),
                GameFactory.grid.solid({ id: 61, x: 140, y: 14, w: 10, h: 1, layout: "board" }),
                GameFactory.grid.solid({ id: 62, x: 140, y: 15, w: 10, h: 5 }),
                GameFactory.grid.solid({ id: 63, x: 140, y: 53, w: 3, h: 1, layout: "board" }),
                GameFactory.grid.solid({ id: 64, x: 140, y: 62, w: 3, h: 1, layout: "board" }),
                GameFactory.grid.booster({ id: 65, x: 144, y: 107, w: 4, h: 2, boostSpeed: 32 }),
                GameFactory.grid.solid({ id: 66, x: 146, y: 58, w: 10, h: 2 }),
                GameFactory.grid.solid({ id: 67, x: 52, y: 97, w: 3, h: 4, layout: "groundBottomCap" }),
                GameFactory.grid.solid({ id: 68, x: 61, y: 97, w: 3, h: 4, layout: "groundBottomCap" }),
                GameFactory.grid.solid({ id: 69, x: 49, y: 105, w: 2, h: 1, layout: "board" }),
                GameFactory.grid.solid({ id: 70, x: 110, y: 106.5, w: 2, h: 5, layout: "groundTopCap" }),
                GameFactory.grid.solid({ id: 71, x: 96, y: 96, w: 6, h: 4, layout: "groundLeftBottomEdgeCap" }),
                GameFactory.grid.solid({ id: 72, x: 98, y: 88, w: 4, h: 3, layout: "groundLeftCap" }),
                GameFactory.grid.solid({ id: 73, x: 31, y: 94, w: 3, h: 1, layout: "board" }),
                GameFactory.grid.solid({ id: 74, x: 16, y: 90, w: 12, h: 5 }),
                GameFactory.grid.solid({ id: 75, x: 16, y: 86, w: 4, h: 5, layout: "groundTopLeftEdgeCap" }),
                GameFactory.grid.solid({ id: 76, x: 4, y: 89, w: 13, h: 4, layout: "groundLeftCap" }),
                GameFactory.grid.solid({ id: 77, x: 4, y: 72, w: 7, h: 18, layout: "groundTopLeftEdgeCap" }),
                GameFactory.grid.solid({ id: 78, x: 10, y: 77, w: 8, h: 3, layout: "groundRightCap" }),
                GameFactory.grid.solid({ id: 79, x: 21, y: 81, w: 4, h: 1, layout: "board" }),
                GameFactory.grid.solid({ id: 80, x: 10, y: 72, w: 4, h: 3, layout: "groundRightTopEdgeCap" }),
                GameFactory.grid.solid({ id: 81, x: 6, y: 67, w: 4, h: 6, layout: "groundTopCap" }),
                GameFactory.grid.solid({ id: 82, x: 10, y: 18, w: 2, h: 1, layout: "boardRightCap" }),
                GameFactory.grid.solid({ id: 83, x: 16, y: 14, w: 2, h: 1, layout: "boardLeftCap" }),
                GameFactory.grid.solid({ id: 84, x: 9, y: 22, w: 5, h: 3, layout: "groundRightCap" }),
                GameFactory.grid.solid({ id: 85, x: 18, y: 21, w: 20, h: 16, layout: "ground" }),
                GameFactory.grid.solid({ id: 86, x: 37, y: 26, w: 16, h: 11, layout: "groundRightBottomEdgeCap" }),
                GameFactory.grid.solid({ id: 87, x: 47, y: 22, w: 6, h: 5, layout: "groundTopRightEdgeCap" }),
                GameFactory.grid.solid({ id: 88, x: 72, y: 34, w: 2, h: 1, layout: "boardLeftCap" }),
                GameFactory.grid.booster({ id: 89, x: 68, y: 34, w: 2, h: 1, boostSpeed: 24 }),
                GameFactory.grid.solid({ id: 90, x: 71, y: 106, w: 7, h: 3, layout: "groundRightCap" }),
                GameFactory.grid.solid({ id: 91, x: 4, y: 96, w: 5, h: 1, layout: "board" }),
                GameFactory.grid.solid({ id: 92, x: 151, y: 100, w: 4, h: 11, layout: "groundTopCap" }),
                GameFactory.grid.solid({ id: 93, x: 148, y: 100, w: 4, h: 6, layout: "groundLeftTopEdgeCap" }),
                GameFactory.grid.solid({ id: 94, x: 164, y: 70, w: 2, h: 32 }),
                GameFactory.grid.solid({ id: 95, x: 170, y: 70, w: 4, h: 41, layout: "groundTopCap" }),
                GameFactory.grid.solid({ id: 96, x: 172, y: 70, w: 16, h: 4, layout: "groundRightTopEdgeCap" }),
                GameFactory.grid.solid({ id: 97, x: 190, y: 70, w: 2, h: 4 }),
                GameFactory.grid.solid({ id: 98, x: 162, y: 84, w: 2, h: 1, layout: "boardLeftCap" }),
                GameFactory.grid.booster({ id: 99, x: 176, y: 108, w: 14, h: 2, boostSpeed: 44 }),
                GameFactory.grid.solid({ id: 100, x: 27, y: 36, w: 10, h: 6, layout: "groundBottomCap" }),
                GameFactory.grid.solid({ id: 101, x: 43, y: 40, w: 10, h: 3 }),
                GameFactory.grid.solid({ id: 102, x: 160, y: 3, w: 6, h: 10, layout: "groundBottomCap" }),
                GameFactory.grid.solid({ id: 103, x: 148, y: 28, w: 20, h: 4 }),
                GameFactory.grid.booster({ id: 104, x: 153, y: 27, w: 3, h: 1, boostSpeed: 30 }),
                GameFactory.grid.solid({ id: 105, x: 178, y: 10, w: 4, h: 4 }),
                GameFactory.grid.solid({ id: 106, x: 170, y: 19, w: 3, h: 40 }),
                GameFactory.grid.booster({ id: 107, x: 168, y: 53, w: 2, h: 1, boostSpeed: 36 }),
                GameFactory.grid.solid({ id: 108, x: 172, y: 19, w: 18, h: 3, layout: "groundRightTopEdgeCap" }),
                GameFactory.grid.solid({ id: 109, x: 188, y: 10, w: 2, h: 10, layout: "groundTopRightEdgeCap" }),
                GameFactory.grid.solid({ id: 110, x: 182, y: 3, w: 5, h: 3, layout: "groundBottomCap" }),
                GameFactory.grid.solid({ id: 111, x: 172, y: 56, w: 6, h: 3, layout: "groundRightBottomEdgeCap" }),
                GameFactory.grid.solid({ id: 112, x: 179, y: 56, w: 14, h: 3 }),
                GameFactory.grid.solid({ id: 113, x: 175, y: 25, w: 18, h: 2 }),
                GameFactory.grid.solid({ id: 114, x: 172, y: 30, w: 18, h: 2, layout: "groundRightCap" }),
                GameFactory.grid.solid({ id: 115, x: 175, y: 33, w: 18, h: 2 }),
                GameFactory.grid.solid({ id: 116, x: 172, y: 36, w: 18, h: 2, layout: "groundRightCap" }),
                GameFactory.grid.solid({ id: 117, x: 172, y: 41, w: 12, h: 2, layout: "groundRightCap" }),
                GameFactory.grid.solid({ id: 118, x: 185, y: 41, w: 8, h: 2 }),
                GameFactory.grid.solid({ id: 119, x: 154, y: 105, w: 4, h: 3, layout: "groundRightCap" }),
                //custom
                GameFactory.grid.solid({ id: 120, x: 36, y: 109, w: 3, h: 2, layout: "groundTopCap" }),
                GameFactory.grid.solid({ id: 121, x: 41, y: 109, w: 2, h: 2, layout: "groundTopCap" }),
            ],
            elevators: [
                GameFactory.grid.elevator({ id: 1001, startX: 166, startY: 109, w: 4, h: 1, targetX: 166, targetY: 70, speed: 8, waitTime: 1500 }),
                GameFactory.grid.elevator({ id: 1002, startX: 37, startY: 71, w: 6, h: 1, targetX: 37, targetY: 41, speed: 8, waitTime: 1500 }),
                GameFactory.grid.elevator({ id: 1003, startX: 150, startY: 14, w: 6, h: 1, targetX: 182, targetY: 14, speed: 6, waitTime: 1500 }),
            ],
            enemies: [
                GameFactory.grid.enemy({ id: 1, minX: 17, maxX: 29, y: 102, speed: 1.5, health: 5, mainColor: "#fa9bdd", secondaryColor: "#710952" }),
                GameFactory.grid.enemy({ id: 2, minX: 43, maxX: 55, y: 108, speed: 1.5, health: 5, mainColor: "#fa9bdd", secondaryColor: "#710952" }),
                GameFactory.grid.enemy({ id: 3, minX: 66, maxX: 72, y: 103, speed: 1.5, health: 5, mainColor: "#fa9bdd", secondaryColor: "#710952" }),
                GameFactory.grid.enemy({ id: 4, minX: 79, maxX: 91, y: 97, speed: 2, health: 15, mainColor: "#fa9bdd", secondaryColor: "#3b1158" }),
                GameFactory.grid.enemy({ id: 5, minX: 110, maxX: 140, y: 104.5, speed: 2, health: 15, mainColor: "#fa9bdd", secondaryColor: "#3b1158" }),
                GameFactory.grid.enemy({ id: 6, minX: 130, maxX: 142, y: 88, speed: 3, health: 20, mainColor: "#fa9bdd", secondaryColor: "#3d83b3" }),
                GameFactory.grid.enemy({ id: 7, minX: 170, maxX: 188, y: 68, speed: 3, health: 20, mainColor: "#fa9bdd", secondaryColor: "#3d83b3" }),
                GameFactory.grid.enemy({ id: 8, minX: 120, maxX: 130, y: 66, speed: 2, health: 15, mainColor: "#fa9bdd", secondaryColor: "#3b1158" }),
                GameFactory.grid.enemy({ id: 9, minX: 20, maxX: 28, y: 88, speed: 2, health: 15, mainColor: "#fa9bdd", secondaryColor: "#3b1158" }),
                GameFactory.grid.enemy({ id: 10, minX: 15, maxX: 22, y: 64, speed: 1.5, health: 5, mainColor: "#fa9bdd", secondaryColor: "#710952" }),
                GameFactory.grid.enemy({ id: 11, minX: 47, maxX: 53, y: 20, speed: 2, health: 15, mainColor: "#fa9bdd", secondaryColor: "#3b1158" }),
                GameFactory.grid.enemy({ id: 12, minX: 48, maxX: 62, y: 76, speed: 3, health: 20, mainColor: "#fa9bdd", secondaryColor: "#3d83b3" }),
                GameFactory.grid.enemy({ id: 13, minX: 63, maxX: 67, y: 12, speed: 2, health: 15, mainColor: "#fa9bdd", secondaryColor: "#3b1158" }),
                GameFactory.grid.enemy({ id: 14, minX: 86, maxX: 116, y: 18, speed: 3, health: 20, mainColor: "#fa9bdd", secondaryColor: "#3d83b3" }),
                GameFactory.grid.enemy({ id: 15, minX: 122, maxX: 140, y: 16, speed: 3, health: 20, mainColor: "#fa9bdd", secondaryColor: "#3d83b3" }),
                GameFactory.grid.enemy({ id: 16, minX: 140, maxX: 150, y: 12, speed: 4, health: 50, mainColor: "#68eef2", secondaryColor: "#3b1158" }),
                GameFactory.grid.enemy({ id: 17, minX: 156, maxX: 168, y: 26, speed: 2, health: 15, mainColor: "#fa9bdd", secondaryColor: "#3b1158" }),
                GameFactory.grid.enemy({ id: 18, minX: 173, maxX: 190, y: 28, speed: 3, health: 20, mainColor: "#fa9bdd", secondaryColor: "#3d83b3" }),
                GameFactory.grid.enemy({ id: 19, minX: 173, maxX: 184, y: 39, speed: 4, health: 50, mainColor: "#68eef2", secondaryColor: "#3b1158" }),
                GameFactory.grid.enemy({ id: 20, minX: 173, maxX: 178, y: 54, speed: 2, health: 15, mainColor: "#fa9bdd", secondaryColor: "#3b1158" }),
                GameFactory.grid.enemy({ id: 21, minX: 148, maxX: 155, y: 98, speed: 2, health: 15, mainColor: "#fa9bdd", secondaryColor: "#3b1158" }),
                GameFactory.grid.enemy({ id: 22, minX: 106, maxX: 115, y: 43, speed: 1.5, health: 5, mainColor: "#fa9bdd", secondaryColor: "#710952" }),
                GameFactory.grid.enemy({ id: 23, minX: 47, maxX: 58, y: 9, speed: 2, health: 15, mainColor: "#fa9bdd", secondaryColor: "#3b1158" }),
            ],
            collectibles: {
                splinters: [
                    GameFactory.grid.splinters({ id: 1, x: 6, y: 94 }),
                    GameFactory.grid.splinters({ id: 2, x: 11, y: 26 }),
                    GameFactory.grid.splinters({ id: 3, x: 58, y: 84 }),
                    GameFactory.grid.splinters({ id: 4, x: 11, y: 109 }),
                    GameFactory.grid.splinters({ id: 5, x: 99, y: 86 }),
                    GameFactory.grid.splinters({ id: 6, x: 1.5, y: 41.5 }),
                    GameFactory.grid.splinters({ id: 7, x: 72.5, y: 32 }),
                    GameFactory.grid.splinters({ id: 8, x: 42, y: 24 }),
                    GameFactory.grid.splinters({ id: 9, x: 8.5, y: 4 }),
                    GameFactory.grid.splinters({ id: 10, x: 54, y: 30 }),
                    GameFactory.grid.splinters({ id: 11, x: 42, y: 84 }),
                    GameFactory.grid.splinters({ id: 12, x: 149, y: 108 }),
                    GameFactory.grid.splinters({ id: 13, x: 47, y: 10 }),
                    GameFactory.grid.splinters({ id: 14, x: 116.5, y: 25.5 }),
                    GameFactory.grid.splinters({ id: 15, x: 110, y: 48 }),
                    GameFactory.grid.splinters({ id: 16, x: 73, y: 109 }),
                    GameFactory.grid.splinters({ id: 17, x: 167, y: 8 }),
                    GameFactory.grid.splinters({ id: 18, x: 11.5, y: 70 }),
                    GameFactory.grid.splinters({ id: 19, x: 9, y: 54 }),
                    GameFactory.grid.splinters({ id: 20, x: 43, y: 109 }),
                    GameFactory.grid.splinters({ id: 21, x: 174, y: 109 }),
                    GameFactory.grid.splinters({ id: 22, x: 162.5, y: 82 }),
                    GameFactory.grid.splinters({ id: 23, x: 51, y: 38 }),
                    GameFactory.grid.splinters({ id: 24, x: 48, y: 52 }),
                    GameFactory.grid.splinters({ id: 25, x: 179.5, y: 5 }),
                    GameFactory.grid.splinters({ id: 26, x: 165, y: 40 }),
                    GameFactory.grid.splinters({ id: 27, x: 174, y: 34 }),
                    GameFactory.grid.splinters({ id: 28, x: 92, y: 54 }),
                    GameFactory.grid.splinters({ id: 29, x: 190, y: 67 }),
                    GameFactory.grid.splinters({ id: 30, x: 156, y: 109 }),
                ],
                coins: [
                    ...GameFactory.grid.columnOfCollectibles({ startId: 1, count: 4, x: 1, y: 8, gap: 1 }),
                    ...GameFactory.grid.columnOfCollectibles({ startId: 5, count: 4, x: 1, y: 9, gap: 1 }),
                    ...GameFactory.grid.columnOfCollectibles({ startId: 9, count: 4, x: 4.5, y: 67.5, gap: 1 }),
                    ...GameFactory.grid.columnOfCollectibles({ startId: 13, count: 20, x: 4, y: 22, gap: 1 }),
                    ...GameFactory.grid.rowOfCollectibles({ startId: 33, count: 2, x: 5, y: 21, gap: 1 }),
                    ...GameFactory.grid.columnOfCollectibles({ startId: 35, count: 20, x: 5, y: 22, gap: 1 }),
                    ...GameFactory.grid.rowOfCollectibles({ startId: 55, count: 2, x: 6, y: 20, gap: 1 }),
                    GameFactory.grid.coins({ id: 57, x: 11, y: 105.5 }),
                    ...GameFactory.grid.rowOfCollectibles({ startId: 58, count: 3, x: 11, y: 75.5, gap: 1 }),
                    ...GameFactory.grid.columnOfCollectibles({ startId: 61, count: 7, x: 12, y: 81, gap: 1 }),
                    ...GameFactory.grid.columnOfCollectibles({ startId: 68, count: 7, x: 13, y: 81, gap: 1 }),
                    ...GameFactory.grid.columnOfCollectibles({ startId: 75, count: 7, x: 14, y: 81, gap: 1 }),
                    ...GameFactory.grid.rowOfCollectibles({ startId: 82, count: 8, x: 19, y: 102, gap: 1 }),
                    GameFactory.grid.coins({ id: 90, x: 18.5, y: 48 }),
                    GameFactory.grid.coins({ id: 91, x: 23.5, y: 58 }),
                    GameFactory.grid.coins({ id: 92, x: 24, y: 8 }),
                    ...GameFactory.grid.rowOfCollectibles({ startId: 93, count: 2, x: 25, y: 7, gap: 1 }),
                    ...GameFactory.grid.columnOfCollectibles({ startId: 95, count: 2, x: 25, y: 50, gap: 1 }),
                    ...GameFactory.grid.columnOfCollectibles({ startId: 97, count: 2, x: 26, y: 50, gap: 1 }),
                    ...GameFactory.grid.rowOfCollectibles({ startId: 99, count: 5, x: 26, y: 68, gap: 1 }),
                    GameFactory.grid.coins({ id: 104, x: 27, y: 8 }),
                    ...GameFactory.grid.rowOfCollectibles({ startId: 105, count: 8, x: 37, y: 105, gap: 1 }),
                    ...GameFactory.grid.columnOfCollectibles({ startId: 113, count: 3, x: 45, y: 5, gap: 1 }),
                    ...GameFactory.grid.columnOfCollectibles({ startId: 116, count: 3, x: 46, y: 5, gap: 1 }),
                    ...GameFactory.grid.rowOfCollectibles({ startId: 119, count: 12, x: 49, y: 72, gap: 1 }),
                    ...GameFactory.grid.rowOfCollectibles({ startId: 131, count: 12, x: 49, y: 76, gap: 1 }),
                    ...GameFactory.grid.rowOfCollectibles({ startId: 143, count: 6, x: 55, y: 92, gap: 1 }),
                    ...GameFactory.grid.rowOfCollectibles({ startId: 149, count: 6, x: 55, y: 93, gap: 1 }),
                    ...GameFactory.grid.rowOfCollectibles({ startId: 155, count: 4, x: 56, y: 99, gap: 1 }),
                    ...GameFactory.grid.rowOfCollectibles({ startId: 159, count: 4, x: 56, y: 100, gap: 1 }),
                    ...GameFactory.grid.rowOfCollectibles({ startId: 163, count: 2, x: 68, y: 99, gap: 1 }),
                    ...GameFactory.grid.rowOfCollectibles({ startId: 165, count: 2, x: 68, y: 100, gap: 1 }),
                    ...GameFactory.grid.columnOfCollectibles({ startId: 167, count: 2, x: 72, y: 21, gap: 1 }),
                    ...GameFactory.grid.columnOfCollectibles({ startId: 169, count: 2, x: 73, y: 21, gap: 1 }),
                    ...GameFactory.grid.rowOfCollectibles({ startId: 171, count: 8, x: 75, y: 64, gap: 1 }),
                    ...GameFactory.grid.rowOfCollectibles({ startId: 179, count: 8, x: 75, y: 65, gap: 1 }),
                    ...GameFactory.grid.columnOfCollectibles({ startId: 187, count: 5, x: 77, y: 19, gap: 1 }),
                    ...GameFactory.grid.columnOfCollectibles({ startId: 192, count: 5, x: 77, y: 31, gap: 1 }),
                    ...GameFactory.grid.columnOfCollectibles({ startId: 197, count: 8, x: 78, y: 77, gap: 1 }),
                    ...GameFactory.grid.columnOfCollectibles({ startId: 205, count: 5, x: 79, y: 25, gap: 1 }),
                    ...GameFactory.grid.columnOfCollectibles({ startId: 210, count: 5, x: 79, y: 37, gap: 1 }),
                    ...GameFactory.grid.columnOfCollectibles({ startId: 215, count: 8, x: 79, y: 77, gap: 1 }),
                    ...GameFactory.grid.rowOfCollectibles({ startId: 223, count: 3, x: 83, y: 21, gap: 1 }),
                    ...GameFactory.grid.rowOfCollectibles({ startId: 226, count: 3, x: 83, y: 22, gap: 1 }),
                    ...GameFactory.grid.rowOfCollectibles({ startId: 229, count: 3, x: 83, y: 23, gap: 1 }),
                    ...GameFactory.grid.rowOfCollectibles({ startId: 232, count: 8, x: 83, y: 108, gap: 1 }),
                    ...GameFactory.grid.rowOfCollectibles({ startId: 240, count: 28, x: 87, y: 18, gap: 1 }),
                    ...GameFactory.grid.rowOfCollectibles({ startId: 268, count: 6, x: 90, y: 71, gap: 1 }),
                    ...GameFactory.grid.rowOfCollectibles({ startId: 274, count: 6, x: 90, y: 72, gap: 1 }),
                    ...GameFactory.grid.rowOfCollectibles({ startId: 280, count: 4, x: 94, y: 106, gap: 1 }),
                    ...GameFactory.grid.rowOfCollectibles({ startId: 284, count: 3, x: 97, y: 92, gap: 1 }),
                    ...GameFactory.grid.rowOfCollectibles({ startId: 287, count: 3, x: 97, y: 93, gap: 1 }),
                    ...GameFactory.grid.rowOfCollectibles({ startId: 290, count: 3, x: 97, y: 94, gap: 1 }),
                    ...GameFactory.grid.columnOfCollectibles({ startId: 293, count: 24, x: 103, y: 50, gap: 1 }),
                    ...GameFactory.grid.rowOfCollectibles({ startId: 317, count: 9, x: 106, y: 42, gap: 1 }),
                    ...GameFactory.grid.rowOfCollectibles({ startId: 326, count: 9, x: 106, y: 43, gap: 1 }),
                    ...GameFactory.grid.rowOfCollectibles({ startId: 335, count: 26, x: 112, y: 108.75, gap: 1 }),
                    ...GameFactory.grid.columnOfCollectibles({ startId: 361, count: 8, x: 115, y: 64, gap: 1 }),
                    ...GameFactory.grid.rowOfCollectibles({ startId: 369, count: 2, x: 116, y: 21, gap: 1 }),
                    ...GameFactory.grid.rowOfCollectibles({ startId: 371, count: 2, x: 116, y: 22, gap: 1 }),
                    ...GameFactory.grid.rowOfCollectibles({ startId: 373, count: 5, x: 121, y: 83, gap: 1 }),
                    ...GameFactory.grid.rowOfCollectibles({ startId: 378, count: 5, x: 121, y: 84, gap: 1 }),
                    ...GameFactory.grid.rowOfCollectibles({ startId: 383, count: 4, x: 124, y: 24, gap: 1 }),
                    ...GameFactory.grid.rowOfCollectibles({ startId: 387, count: 4, x: 124, y: 25, gap: 1 }),
                    ...GameFactory.grid.rowOfCollectibles({ startId: 391, count: 10, x: 140, y: 7, gap: 1 }),
                    ...GameFactory.grid.rowOfCollectibles({ startId: 401, count: 10, x: 140, y: 8, gap: 1 }),
                    ...GameFactory.grid.rowOfCollectibles({ startId: 411, count: 10, x: 140, y: 9, gap: 1 }),
                    ...GameFactory.grid.rowOfCollectibles({ startId: 421, count: 10, x: 140, y: 10, gap: 1 }),
                    GameFactory.grid.coins({ id: 431, x: 141, y: 59 }),
                    ...GameFactory.grid.rowOfCollectibles({ startId: 432, count: 2, x: 145, y: 109, gap: 1 }),
                    ...GameFactory.grid.columnOfCollectibles({ startId: 434, count: 4, x: 148, y: 53, gap: 1 }),
                    ...GameFactory.grid.rowOfCollectibles({ startId: 438, count: 18, x: 19, y: 19, gap: 1 }),
                    ...GameFactory.grid.rowOfCollectibles({ startId: 456, count: 7, x: 39, y: 22, gap: 1 }),
                    ...GameFactory.grid.rowOfCollectibles({ startId: 463, count: 7, x: 39, y: 23, gap: 1 }),
                    ...GameFactory.grid.columnOfCollectibles({ startId: 470, count: 20, x: 0, y: 21, gap: 1 }),
                    ...GameFactory.grid.columnOfCollectibles({ startId: 490, count: 10, x: 1, y: 45, gap: 1 }),
                    GameFactory.grid.coins({ id: 500, x: 10.5, y: 15 }),
                    ...GameFactory.grid.rowOfCollectibles({ startId: 501, count: 10, x: 176, y: 75, gap: 1 }),
                    ...GameFactory.grid.rowOfCollectibles({ startId: 511, count: 10, x: 176, y: 76, gap: 1 }),
                    ...GameFactory.grid.rowOfCollectibles({ startId: 521, count: 10, x: 176, y: 77, gap: 1 }),
                    ...GameFactory.grid.rowOfCollectibles({ startId: 531, count: 10, x: 176, y: 78, gap: 1 }),
                    ...GameFactory.grid.rowOfCollectibles({ startId: 541, count: 10, x: 176, y: 79, gap: 1 }),
                    ...GameFactory.grid.rowOfCollectibles({ startId: 551, count: 10, x: 176, y: 80, gap: 1 }),
                    ...GameFactory.grid.rowOfCollectibles({ startId: 561, count: 10, x: 176, y: 81, gap: 1 }),
                    ...GameFactory.grid.rowOfCollectibles({ startId: 571, count: 10, x: 176, y: 82, gap: 1 }),
                    ...GameFactory.grid.rowOfCollectibles({ startId: 581, count: 10, x: 176, y: 83, gap: 1 }),
                    ...GameFactory.grid.rowOfCollectibles({ startId: 591, count: 10, x: 176, y: 84, gap: 1 }),
                    ...GameFactory.grid.rowOfCollectibles({ startId: 601, count: 10, x: 176, y: 85, gap: 1 }),
                    ...GameFactory.grid.rowOfCollectibles({ startId: 611, count: 10, x: 176, y: 86, gap: 1 }),
                    ...GameFactory.grid.rowOfCollectibles({ startId: 621, count: 10, x: 176, y: 87, gap: 1 }),
                    ...GameFactory.grid.rowOfCollectibles({ startId: 631, count: 10, x: 176, y: 88, gap: 1 }),
                    ...GameFactory.grid.rowOfCollectibles({ startId: 641, count: 10, x: 176, y: 89, gap: 1 }),
                    ...GameFactory.grid.rowOfCollectibles({ startId: 650, count: 8, x: 43, y: 38, gap: 1 }),
                    ...GameFactory.grid.rowOfCollectibles({ startId: 658, count: 6, x: 160, y: 13, gap: 1 }),
                    ...GameFactory.grid.rowOfCollectibles({ startId: 664, count: 10, x: 173, y: 38, gap: 1 }),
                    ...GameFactory.grid.rowOfCollectibles({ startId: 674, count: 10, x: 173, y: 39, gap: 1 }),
                    ...GameFactory.grid.rowOfCollectibles({ startId: 684, count: 10, x: 173, y: 40, gap: 1 }),
                    ...GameFactory.grid.columnOfCollectibles({ startId: 694, count: 6, x: 174, y: 48, gap: 1 }),
                    ...GameFactory.grid.columnOfCollectibles({ startId: 700, count: 6, x: 175, y: 48, gap: 1 }),
                    ...GameFactory.grid.columnOfCollectibles({ startId: 706, count: 6, x: 176, y: 48, gap: 1 }),
                    ...GameFactory.grid.columnOfCollectibles({ startId: 712, count: 12, x: 190, y: 10, gap: 1 }),
                    ...GameFactory.grid.columnOfCollectibles({ startId: 724, count: 12, x: 191, y: 10, gap: 1 }),
                    ...GameFactory.grid.columnOfCollectibles({ startId: 736, count: 8, x: 173, y: 22, gap: 1 }),
                    ...GameFactory.grid.columnOfCollectibles({ startId: 744, count: 8, x: 174, y: 22, gap: 1 }),
                    ...GameFactory.grid.columnOfCollectibles({ startId: 752, count: 32, x: 166, y: 70, gap: 1 }),
                    ...GameFactory.grid.columnOfCollectibles({ startId: 784, count: 32, x: 169, y: 70, gap: 1 }),
                    ...GameFactory.grid.columnOfCollectibles({ startId: 816, count: 7, x: 149, y: 88, gap: 1 }),
                    ...GameFactory.grid.columnOfCollectibles({ startId: 823, count: 7, x: 150, y: 88, gap: 1 }),
                    ...GameFactory.grid.columnOfCollectibles({ startId: 830, count: 7, x: 151, y: 88, gap: 1 }),
                    ...GameFactory.grid.columnOfCollectibles({ startId: 837, count: 7, x: 152, y: 88, gap: 1 }),
                    ...GameFactory.grid.columnOfCollectibles({ startId: 844, count: 7, x: 153, y: 88, gap: 1 }),
                    ...GameFactory.grid.rowOfCollectibles({ startId: 851, count: 7, x: 159, y: 20, gap: 1 }),
                    ...GameFactory.grid.rowOfCollectibles({ startId: 858, count: 7, x: 159, y: 21, gap: 1 }),
                    ...GameFactory.grid.rowOfCollectibles({ startId: 865, count: 7, x: 159, y: 22, gap: 1 }),
                    ...GameFactory.grid.rowOfCollectibles({ startId: 872, count: 7, x: 159, y: 23, gap: 1 }),
                    ...GameFactory.grid.rowOfCollectibles({ startId: 879, count: 7, x: 159, y: 24, gap: 1 }),
                    ...GameFactory.grid.rowOfCollectibles({ startId: 886, count: 7, x: 159, y: 25, gap: 1 }),
                    ...GameFactory.grid.rowOfCollectibles({ startId: 893, count: 7, x: 159, y: 26, gap: 1 }),
                ],
                hearts: [
                    GameFactory.grid.hearts({ id: 1, x: 124, y: 63 }),
                    GameFactory.grid.hearts({ id: 2, x: 136, y: 102 }),
                    GameFactory.grid.hearts({ id: 3, x: 132, y: 46 }),
                    GameFactory.grid.hearts({ id: 4, x: 16.5, y: 11 }),
                    GameFactory.grid.hearts({ id: 5, x: 158, y: 9 }),
                    GameFactory.grid.hearts({ id: 6, x: 95.5, y: 103 }),
                ],
            },
            spikes: [
                GameFactory.grid.spike({ id: 1, x: 103, y: 109, variant: 1 }),
                GameFactory.grid.spike({ id: 2, x: 104, y: 109, variant: 2 }),
                GameFactory.grid.spike({ id: 3, x: 105, y: 109, variant: 1 }),
                GameFactory.grid.spike({ id: 4, x: 39, y: 109, variant: 1 }),
                GameFactory.grid.spike({ id: 5, x: 40, y: 109, variant: 2 }),
                GameFactory.grid.spike({ id: 6, x: 77, y: 69, variant: 1 }),
                GameFactory.grid.spike({ id: 7, x: 78, y: 69, variant: 2 }),
                GameFactory.grid.spike({ id: 8, x: 38, y: 10, variant: 1 }),
                GameFactory.grid.spike({ id: 9, x: 39, y: 10, variant: 2 }),
                GameFactory.grid.spike({ id: 10, x: 40, y: 10, variant: 2 }),
                GameFactory.grid.spike({ id: 11, x: 149, y: 57, variant: 1 }),
                GameFactory.grid.spike({ id: 12, x: 150, y: 57, variant: 1 }),
                GameFactory.grid.spike({ id: 13, x: 151, y: 57, variant: 2 }),
                GameFactory.grid.spike({ id: 14, x: 152, y: 57, variant: 2 }),
                GameFactory.grid.spike({ id: 15, x: 190, y: 109, variant: 1 }),
                GameFactory.grid.spike({ id: 16, x: 191, y: 109, variant: 2 }),
                ...GameFactory.grid.rowOfSpikes({ startId: 17, count: 14, x: 172, y: 18 }),
                ...GameFactory.grid.rowOfSpikes({ startId: 31, count: 4, x: 72, y: 105 }),
                GameFactory.grid.spike({ id: 35, x: 10, y: 21, variant: 1 }),
                GameFactory.grid.spike({ id: 36, x: 11, y: 21, variant: 2 }),
                ...GameFactory.grid.rowOfSpikes({ startId: 37, count: 3, x: 52, y: 101, position: "up" }),
                ...GameFactory.grid.rowOfSpikes({ startId: 40, count: 3, x: 61, y: 101, position: "up" }),
                ...GameFactory.grid.rowOfSpikes({ startId: 43, count: 15, x: 20, y: 17, position: "up" }),
            ],
            preBackgroundItems: [
                GameFactory.grid.environment.elevatorPanel({ x: 165, y: 108 }),
                GameFactory.grid.environment.elevatorPanel({ x: 35.5, y: 70 }),
                GameFactory.grid.environment.elevatorPanel({ x: 148, y: 12 }),
                GameFactory.grid.environment.elevatorPanel({ x: 180, y: 8 }),
                GameFactory.grid.environment.elevatorPanel({ x: 43, y: 38.5 }),
                GameFactory.grid.environment.elevatorPanel({ x: 171, y: 68 }),
            ],
            backgroundItems: [
                GameFactory.grid.environment.wallPlant001({ x: 2, y: 40 }),
                GameFactory.grid.environment.plant003({ x: 5, y: 110 }),
                GameFactory.grid.environment.plant004({ x: 6, y: 110 }),
                GameFactory.grid.environment.plant003({ x: 7, y: 67 }),
                GameFactory.grid.environment.plant003({ x: 10, y: 110 }),
                GameFactory.grid.environment.wallPlant001({ x: 13, y: 3 }),
                GameFactory.grid.environment.flower002({ x: 15, y: 109 }),
                GameFactory.grid.environment.plant004({ x: 16, y: 86 }),
                GameFactory.grid.environment.plant003({ x: 20, y: 90 }),
                GameFactory.grid.environment.plant003({ x: 21, y: 90 }),
                GameFactory.grid.environment.plant004({ x: 22, y: 90 }),
                GameFactory.grid.environment.wallPlant001({ x: 22, y: 94 }),
                GameFactory.grid.environment.plant003({ x: 23, y: 21 }),
                GameFactory.grid.environment.plant004({ x: 25, y: 21 }),
                GameFactory.grid.environment.plate001({ x: 25, y: 90 }),
                GameFactory.grid.environment.plant003({ x: 31, y: 21 }),
                GameFactory.grid.environment.plant004({ x: 32, y: 21 }),
                GameFactory.grid.environment.wallPlant001({ x: 33, y: 3 }),
                GameFactory.grid.environment.plant004({ x: 34, y: 21 }),
                GameFactory.grid.environment.plant004({ x: 35, y: 21 }),
                GameFactory.grid.environment.plant003({ x: 36, y: 21 }),
                GameFactory.grid.environment.plant003({ x: 38, y: 26 }),
                GameFactory.grid.environment.wallPlant001({ x: 38, y: 103 }),
                GameFactory.grid.environment.plant004({ x: 40, y: 26 }),
                GameFactory.grid.environment.plant004({ x: 41, y: 11 }),
                GameFactory.grid.environment.wallPlant001({ x: 41, y: 16 }),
                GameFactory.grid.environment.flower001({ x: 42, y: 24 }),
                GameFactory.grid.environment.plant003({ x: 42, y: 11 }),
                GameFactory.grid.environment.plant004({ x: 43, y: 11 }),
                GameFactory.grid.environment.wallPlant001({ x: 44, y: 16 }),
                GameFactory.grid.environment.plant003({ x: 44, y: 98 }),
                GameFactory.grid.environment.plant003({ x: 63, y: 110 }),
                GameFactory.grid.environment.plate001({ x: 68, y: 105 }),
                GameFactory.grid.environment.plate001({ x: 74, y: 18 }),
                GameFactory.grid.environment.plate001({ x: 75, y: 70 }),
                GameFactory.grid.environment.wallPlant001({ x: 77, y: 73 }),
                GameFactory.grid.environment.plate001({ x: 79, y: 70 }),
                GameFactory.grid.environment.plant004({ x: 81, y: 70 }),
                GameFactory.grid.environment.plant002({ x: 91, y: 110 }),
                GameFactory.grid.environment.wallPlant001({ x: 92, y: 25 }),
                GameFactory.grid.environment.wallPlant001({ x: 98, y: 25 }),
                GameFactory.grid.environment.flower001({ x: 100, y: 108 }),
                GameFactory.grid.environment.plant004({ x: 111, y: 106.5 }),
                GameFactory.grid.environment.wallPlant001({ x: 113, y: 25 }),
                GameFactory.grid.environment.plant001({ x: 118, y: 106.5 }),
                GameFactory.grid.environment.plate001({ x: 126, y: 68 }),
                GameFactory.grid.environment.plant003({ x: 133, y: 110 }),
                GameFactory.grid.environment.plant002({ x: 136, y: 107 }),
                GameFactory.grid.environment.plant004({ x: 148, y: 100 }),
                GameFactory.grid.environment.plant003({ x: 149, y: 28 }),
                GameFactory.grid.environment.wallPlant001({ x: 149, y: 59 }),
                GameFactory.grid.environment.plant004({ x: 149, y: 100 }),
                GameFactory.grid.environment.plant003({ x: 150, y: 100 }),
                GameFactory.grid.environment.plant003({ x: 151, y: 28 }),
                GameFactory.grid.environment.plant003({ x: 151, y: 100 }),
                GameFactory.grid.environment.plant003({ x: 152, y: 100 }),
                GameFactory.grid.environment.plant004({ x: 153, y: 100 }),
                GameFactory.grid.environment.plant003({ x: 154, y: 100 }),
                GameFactory.grid.environment.plant004({ x: 156, y: 28 }),
                GameFactory.grid.environment.wallPlant001({ x: 156, y: 107 }),
                GameFactory.grid.environment.plant004({ x: 157, y: 28 }),
                GameFactory.grid.environment.plant001({ x: 164, y: 70 }),
                GameFactory.grid.environment.plant004({ x: 164, y: 110 }),
                GameFactory.grid.environment.wallPlant001({ x: 169, y: 3 }),
                GameFactory.grid.environment.plant004({ x: 170, y: 70 }),
                GameFactory.grid.environment.plant002({ x: 171, y: 70 }),
                GameFactory.grid.environment.plant004({ x: 172, y: 70 }),
                GameFactory.grid.environment.plant003({ x: 173, y: 36 }),
                GameFactory.grid.environment.plant004({ x: 173, y: 41 }),
                GameFactory.grid.environment.plant001({ x: 173, y: 56 }),
                GameFactory.grid.environment.plant003({ x: 174, y: 36 }),
                GameFactory.grid.environment.plant004({ x: 174, y: 41 }),
                GameFactory.grid.environment.wallPlant001({ x: 174, y: 73 }),
                GameFactory.grid.environment.plant003({ x: 176, y: 33 }),
                GameFactory.grid.environment.plant004({ x: 176, y: 41 }),
                GameFactory.grid.environment.plant003({ x: 180, y: 36 }),
                GameFactory.grid.environment.plant004({ x: 184, y: 70 }),
                GameFactory.grid.environment.wallPlant001({ x: 185, y: 5 }),
                GameFactory.grid.environment.plant001({ x: 186, y: 19 }),
                GameFactory.grid.environment.plant004({ x: 189, y: 33 }),
                GameFactory.grid.environment.plant003({ x: 190, y: 41 }),
                GameFactory.grid.environment.flower001({ x: 190, y: 68 }),
                GameFactory.grid.environment.plant003({ x: 191, y: 41 }),
                GameFactory.grid.environment.plant003({ x: 176, y: 25 }),
                GameFactory.grid.environment.plant003({ x: 177, y: 25 }),
                GameFactory.grid.environment.wallPlant001({ x: 176, y: 26 }),
                GameFactory.grid.environment.wallPlant001({ x: 188, y: 21 }),
                GameFactory.grid.environment.plant003({ x: 186, y: 30 }),
                GameFactory.grid.environment.plant003({ x: 187, y: 30 }),
                GameFactory.grid.environment.plant003({ x: 188, y: 30 }),
                GameFactory.grid.environment.plant004({ x: 182, y: 30 }),
                GameFactory.grid.environment.plant003({ x: 183, y: 30 }),
                GameFactory.grid.environment.plant004({ x: 173, y: 30 }),
                GameFactory.grid.environment.plant003({ x: 174, y: 30 }),
                GameFactory.grid.environment.plant004({ x: 175, y: 56 }),
                GameFactory.grid.environment.plant004({ x: 176, y: 56 }),
                GameFactory.grid.environment.wallPlant001({ x: 175, y: 42 }),
                GameFactory.grid.environment.wallPlant001({ x: 182, y: 42 }),
            ],
            foregroundItems: [
                GameFactory.grid.environment.flower001({ x: 1, y: 19 }),
                GameFactory.grid.environment.plant004({ x: 4, y: 110 }),
                GameFactory.grid.environment.wallPlant001({ x: 8.5, y: 3 }),
                GameFactory.grid.environment.flower002({ x: 8, y: 12 }),
                GameFactory.grid.environment.flower001({ x: 11, y: 70 }),
                GameFactory.grid.environment.plant003({ x: 11, y: 77 }),
                GameFactory.grid.environment.plant002({ x: 11, y: 110 }),
                GameFactory.grid.environment.flower002({ x: 17, y: 86 }),
                GameFactory.grid.environment.plant002({ x: 22, y: 110 }),
                GameFactory.grid.environment.wallPlant001({ x: 28, y: 16 }),
                GameFactory.grid.environment.plant004({ x: 30, y: 110 }),
                GameFactory.grid.environment.flower002({ x: 33, y: 21 }),
                GameFactory.grid.environment.plant003({ x: 33, y: 110 }),
                GameFactory.grid.environment.plant001({ x: 35, y: 11 }),
                GameFactory.grid.environment.plant003({ x: 39, y: 26 }),
                GameFactory.grid.environment.plant001({ x: 41, y: 26 }),
                GameFactory.grid.environment.flower002({ x: 41, y: 97 }),
                GameFactory.grid.environment.flower002({ x: 43, y: 26 }),
                GameFactory.grid.environment.plant002({ x: 43, y: 110 }),
                GameFactory.grid.environment.plant003({ x: 44, y: 11 }),
                GameFactory.grid.environment.plant004({ x: 45, y: 26 }),
                GameFactory.grid.environment.plant004({ x: 46, y: 26 }),
                GameFactory.grid.environment.plant001({ x: 46, y: 110 }),
                GameFactory.grid.environment.plant002({ x: 47, y: 11 }),
                GameFactory.grid.environment.plant004({ x: 52, y: 78 }),
                GameFactory.grid.environment.flower002({ x: 56, y: 11 }),
                GameFactory.grid.environment.plant001({ x: 58, y: 78 }),
                GameFactory.grid.environment.plant001({ x: 59, y: 95 }),
                GameFactory.grid.environment.plant002({ x: 67, y: 105 }),
                GameFactory.grid.environment.plant003({ x: 72, y: 110 }),
                GameFactory.grid.environment.plant001({ x: 73, y: 110 }),
                GameFactory.grid.environment.flower002({ x: 81, y: 18 }),
                GameFactory.grid.environment.plant001({ x: 106, y: 110 }),
                GameFactory.grid.environment.plant003({ x: 113, y: 110 }),
                GameFactory.grid.environment.plant001({ x: 147, y: 58 }),
                GameFactory.grid.environment.plant003({ x: 148, y: 28 }),
                GameFactory.grid.environment.plant003({ x: 150, y: 28 }),
                GameFactory.grid.environment.plant003({ x: 152, y: 28 }),
                GameFactory.grid.environment.flower002({ x: 155, y: 110 }),
                GameFactory.grid.environment.flower001({ x: 173, y: 34 }),
                GameFactory.grid.environment.flower002({ x: 174, y: 110 }),
                GameFactory.grid.environment.flower002({ x: 179, y: 10 }),
                GameFactory.grid.environment.plant001({ x: 190, y: 56 }),
            ],
            exits: [
                GameFactory.grid.exit({ id: 1, x: 185, y: 49, w: 76, h: 108 }),
            ],
            messages: [
                GameFactory.grid.message({ id: "msg-1", x: 0, y: 100, w: 5, h: 10, offsetX: 0, offsetY: -5, lines: MESSAGES.LEVEL_1.INTRO, relatedTo: "viewPort", strategy: "single" }),
                GameFactory.grid.message({ id: "msg-2", x: 6, y: 104, w: 6, h: 6, offsetX: 0, offsetY: -2, lines: MESSAGES.LEVEL_1.JUMP_HINT, relatedTo: "viewPort", strategy: "single" }),
                GameFactory.grid.message({ id: "msg-3", x: 17, y: 100, w: 10, h: 5, offsetX: 0, offsetY: -2, lines: MESSAGES.LEVEL_1.SHOOT_HINT, relatedTo: "viewPort", strategy: "single" }),
                GameFactory.grid.message({ id: "msg-4", x: 78, y: 106, w: 15, h: 4, offsetX: 0, offsetY: 2, lines: MESSAGES.LEVEL_1.CROUCH_HINT, relatedTo: "viewPort", strategy: "single" }),
                GameFactory.grid.message({ id: "msg-5", x: 110, y: 102, w: 30, h: 4, offsetX: 0, offsetY: -2, lines: MESSAGES.LEVEL_1.PAUSE_HINT, relatedTo: "viewPort", strategy: "single" }),
                GameFactory.grid.message({ id: "msg-6", x: 175, y: 62, w: 13, h: 8, offsetX: 0, offsetY: -2, lines: MESSAGES.LEVEL_1.MINI_MAP_HINT, relatedTo: "viewPort", strategy: "multiple" }),
            ],
        };
    },
};
