import { MESSAGES } from "../messages.js";

let _nextCheckpointPlatformId = 9001;

export const GameFactory = {
    GRID: 48,
    SCALE: 3,
    player: (overrides = {}) => ({
        x: 0,
        y: 0,
        prevX: 0,
        prevY: 0,
        w: 36,
        h: 108,
        vx: 0,
        vy: 0,
        life: 5,
        maxLife: 5,
        isHit: false,
        lastHitTime: 0,
        hitCooldown: 1000,
        acceleration: 0.8,
        deceleration: 1.2,
        airAcceleration: 2,
        airDeceleration: 2,
        carryVx: 0,
        carryVxInitial: 0,
        carryStartAt: 0,
        carryDuration: 400,
        speed: 5.8,
        crouchSpeed: 3,
        crouchHeight: 45,
        crouchWidth: 72,
        originalHeight: 108,
        originalWidth: 36,
        airborne: true,
        jump: 16.4,
        jumpPressedByUser: false,
        jumpPressedAt: 0,
        jumpBufferDuration: 80,
        lastGroundedAt: 0,
        coyoteDuration: 80,
        onGroundId: null,
        onGroundType: null,
        lastGroundId: null,
        lastGroundType: null,
        coinsCount: 0,
        splintersCount: 0,
        facing: "right",
        shooting: false,
        lastShootTime: 0,
        shootingOffsetY: -4,
        shootingCrouchOffsetY: 4,
        shootingOffsetX: 33,
        shootingCrouchOffsetX: 44,
        ...overrides,
    }),
    solid: ({ id, x, y, w, h, layout = "ground", color } = {}) => ({
        id,
        x,
        y,
        w,
        h,
        type: "solid",
        layout,
        ...(color !== undefined && { color }),
    }),
    oneDirection: ({ id, x, y, w, h, layout = "boardOneDirection" } = {}) => ({
        id,
        x,
        y,
        w,
        h,
        type: "oneDirection",
        layout,
    }),
    cracks: ({ id, x, y, w, h, layout = "cracks" } = {}) => ({
        id,
        x,
        y,
        w,
        h,
        type: "solid",
        layout,
    }),
    booster: ({ id, x, y, w, h, boostSpeed = 20 } = {}) => ({
        id,
        x,
        y,
        w,
        h,
        elasticity: 0,
        type: "booster",
        layout: "booster",
        boostSpeed,
    }),
    elevator: ({
        id,
        startX,
        startY,
        w,
        h,
        targetX,
        targetY,
        speed,
        waitTime,
        layout = "brick",
        triggered = false,
    } = {}) => {
        const dx = targetX - startX;
        const dy = targetY - startY;
        const length = Math.hypot(dx, dy);
        return {
            id,
            x: startX,
            y: startY,
            w,
            h,
            startX,
            startY,
            targetX,
            targetY,
            dirX: dx / length,
            dirY: dy / length,
            //the range that makes sense is 2-8
            speed,
            direction: 1,
            waitTime,
            idleUntil: 0,
            triggered,
            type: "elevator",
            layout,
        };
    },
    enemy: ({ id, minX, maxX, y, speed = 1.5, health = 15, ...rest } = {}) => ({
        id,
        minX,
        maxX,
        x: minX,
        y,
        w: 44,
        h: 96,
        prevX: minX,
        prevY: y,
        speed,
        vx: speed,
        health,
        recoilX: 18,
        recoilY: 6,
        isDamaged: false,
        dead: false,
        damage: 1,
        damageTime: 0,
        wasCollidingWithPlayer: false,
        collidingWithPlayerThisFrame: false,
        type: "pill",
        mainColor: "#e84855",
        secondaryColor: "#f7b32b",
        ...rest,
    }),
    exit: ({ id, x, y, w, h, ...rest } = {}) => ({
        id,
        x,
        y,
        w,
        h,
        cordX: 108,
        cordY: 36,
        url: "textures/all-props.png",
        triggerMargin: GameFactory.GRID * 3,
        ...rest,
    }),
    message: ({
        id,
        x,
        y,
        w,
        h,
        offsetX = 0,
        offsetY = 0,
        lines,
        relatedTo = "hitbox",
        strategy = "multiple",
        displayTime,
    } = {}) => ({
        id,
        x,
        y,
        w,
        h,
        offsetX,
        offsetY,
        lines: lines ?? [],
        relatedTo,
        strategy,
        ...(displayTime !== undefined && { displayTime }),
        shown: false,
    }),
    collectible: ({ id, x, y, ...rest } = {}) => ({
        id,
        x,
        y,
        w: 24,
        h: 24,
        collected: false,
        ...rest,
    }),
    weapon: (overrides = {}) => ({
        id: null,
        color: "#ffc300",
        speed: 12,
        shootFrequency: 125,
        ammo: {
            vx: 0,
            vy: 0,
            w: 8,
            h: 8,
            damage: 5,
        },
        ...overrides,
    }),
    cannon: ({ id, x, y, targetY, ...rest } = {}) => ({
        id,
        x,
        y,
        w: 96,
        h: 96,
        targetY,
        color: "#35fffd",
        speed: 8,
        shootFrequency: 2000,
        delay: 0,
        lastShootTime: 0,
        ammo: {
            vx: 0,
            vy: 0,
            w: 8,
            h: 8,
            damage: 1,
            recoilX: 0,
            recoilY: 5,
        },
        ...rest,
    }),
    rowOfCollectibles: ({ startId, count, startX, y, gap } = {}) =>
        Array.from({ length: count }, (_, i) =>
            GameFactory.collectible({
                id: startId + i,
                x: startX + i * gap,
                y,
            }),
        ),
    columnOfCollectibles: ({ startId, count, x, startY, gap } = {}) =>
        Array.from({ length: count }, (_, i) =>
            GameFactory.collectible({
                id: startId + i,
                x,
                y: startY + i * gap,
            }),
        ),
    rowOfSpikes: ({
        startId,
        count,
        startX,
        y,
        position = "down",
        damage = 1,
    } = {}) => {
        const spikeW = 16 * GameFactory.SCALE;
        return Array.from({ length: count }, (_, i) =>
            GameFactory.spike({
                id: startId + i,
                x: startX + i * spikeW,
                y,
                variant: (i % 2) + 1,
                position,
                damage,
            }),
        );
    },
    spike: ({
        id,
        x,
        y,
        variant = 1,
        position = "down",
        damage = 1,
        recoilX = 9,
        recoilY = 9,
        w = 16 * GameFactory.SCALE,
        h = 16 * GameFactory.SCALE,
    } = {}) => ({
        id,
        x,
        y: position === "up" ? y : y + 4,
        w,
        h: position === "up" ? h - 14 : h - 4,
        variant,
        position,
        damage,
        recoilX,
        recoilY: position === "down" ? recoilY : 0,
        type: "spike",
    }),
    environment: {
        checkpoint: ({ id, x, y, w, h, reached = false } = {}) => ({
            id,
            x,
            y,
            w,
            h,
            reached,
        }),
        checkpointBack: ({ x, y, ...rest } = {}) => ({
            x,
            y,
            url: "textures/checkpoint.png",
            cordX: 0,
            cordY: 0,
            w: 16,
            h: 49,
            ...rest,
        }),
        checkpointFront: ({ x, y, ...rest } = {}) => ({
            x,
            y,
            url: "textures/checkpoint.png",
            cordX: 16,
            cordY: 0,
            w: 16,
            h: 49,
            ...rest,
        }),
        plant001: ({ x, y, ...rest } = {}) => ({
            x,
            y,
            url: "textures/tilesets.png",
            cordX: 48,
            cordY: 98,
            w: 32,
            h: 30,
            ...rest,
        }),
        plant002: ({ x, y, ...rest } = {}) => ({
            x,
            y,
            url: "textures/tilesets.png",
            cordX: 16,
            cordY: 100,
            w: 32,
            h: 32,
            ...rest,
        }),
        plant003: ({ x, y, ...rest } = {}) => ({
            x,
            y,
            url: "textures/tilesets.png",
            cordX: 96,
            cordY: 105,
            w: 16,
            h: 21,
            ...rest,
        }),
        plant004: ({ x, y, ...rest } = {}) => ({
            x,
            y,
            url: "textures/tilesets.png",
            cordX: 128,
            cordY: 104,
            w: 16,
            h: 22,
            ...rest,
        }),
        plant005: ({ x, y, ...rest } = {}) => ({
            x,
            y,
            url: "textures/all-props.png",
            cordX: 366,
            cordY: 112,
            w: 32,
            h: 32,
            ...rest,
        }),
        plant006: ({ x, y, ...rest } = {}) => ({
            x,
            y,
            url: "textures/all-props.png",
            cordX: 446,
            cordY: 112,
            w: 32,
            h: 32,
            ...rest,
        }),
        wallPlant001: ({ x, y, ...rest } = {}) => ({
            x,
            y,
            url: "textures/tilesets.png",
            cordX: 128,
            cordY: 48,
            w: 16,
            h: 27,
            ...rest,
        }),
        plate001: ({ x, y, ...rest } = {}) => ({
            x,
            y,
            url: "textures/tilesets.png",
            cordX: 160,
            cordY: 107,
            w: 32,
            h: 21,
            ...rest,
        }),
        flower001: ({ x, y, ...rest } = {}) => ({
            x,
            y,
            url: "textures/props.png",
            cordX: 45,
            cordY: 16,
            w: 32,
            h: 46,
            ...rest,
        }),
        flower002: ({ x, y, ...rest } = {}) => ({
            x,
            y,
            url: "textures/props.png",
            cordX: 4,
            cordY: 32,
            w: 32,
            h: 32,
            ...rest,
        }),
        elevatorPanel: ({ x, y, ...rest } = {}) => ({
            x,
            y,
            url: "textures/elevator.png",
            cordX: 0,
            cordY: 0,
            w: 16,
            h: 48,
            ...rest,
        }),
        wallClean: ({ x, y, w = 16, h = 16, ...rest } = {}) => ({
            x,
            y,
            w: w * GameFactory.SCALE,
            h: h * GameFactory.SCALE,
            solidFill: "#3b1158",
            ...rest,
        }),
        wallSharpLeftTop: ({ x, y, ...rest } = {}) => ({
            x,
            y,
            url: "textures/walls.png",
            cordX: 16,
            cordY: 64,
            w: 32,
            h: 16,
            ...rest,
        }),
        wallSharpLeft: ({ x, y, ...rest } = {}) => ({
            x,
            y,
            url: "textures/walls.png",
            cordX: 16,
            cordY: 80,
            w: 32,
            h: 16,
            ...rest,
        }),
        wallSharpLeftBottom: ({ x, y, ...rest } = {}) => ({
            x,
            y,
            url: "textures/walls.png",
            cordX: 16,
            cordY: 96,
            w: 32,
            h: 16,
            ...rest,
        }),
        wallSharpLeftCol: ({ x, y, count, ...rest } = {}) =>
            Array.from({ length: count }, (_, i) =>
                GameFactory.environment.wallSharpLeft({
                    x,
                    y: y + i * 16 * GameFactory.SCALE,
                    ...rest,
                }),
            ),
        wallSharpRightTop: ({ x, y, ...rest } = {}) => ({
            x,
            y,
            url: "textures/walls.png",
            cordX: 112,
            cordY: 64,
            w: 32,
            h: 16,
            ...rest,
        }),
        wallSharpRight: ({ x, y, ...rest } = {}) => ({
            x,
            y,
            url: "textures/walls.png",
            cordX: 112,
            cordY: 80,
            w: 32,
            h: 16,
            ...rest,
        }),
        wallSharpRightBottom: ({ x, y, ...rest } = {}) => ({
            x,
            y,
            url: "textures/walls.png",
            cordX: 112,
            cordY: 96,
            w: 32,
            h: 16,
            ...rest,
        }),
        wallSharpRightCol: ({ x, y, count, ...rest } = {}) =>
            Array.from({ length: count }, (_, i) =>
                GameFactory.environment.wallSharpRight({
                    x,
                    y: y + i * 16 * GameFactory.SCALE,
                    ...rest,
                }),
            ),
        wallSharpHole: ({ x, y, ...rest } = {}) => ({
            x,
            y,
            url: "textures/walls.png",
            cordX: 64,
            cordY: 64,
            w: 32,
            h: 64,
            ...rest,
        }),
        wallInside: ({ x, y, ...rest } = {}) => ({
            x,
            y,
            url: "textures/tilesets.png",
            cordX: 222,
            cordY: 144,
            w: 16,
            h: 16,
            ...rest,
        }),
    },
    grid: {
        enemy: ({ id, minX, maxX, x = minX, y, speed, health, ...rest } = {}) =>
            GameFactory.enemy({
                id,
                minX: minX * GameFactory.GRID,
                maxX: maxX * GameFactory.GRID,
                y: y * GameFactory.GRID,
                x: x * GameFactory.GRID,
                speed,
                health,
                ...rest,
            }),
        cannon: ({ id, x, y, targetY, ...rest } = {}) =>
            GameFactory.cannon({
                id,
                x: x * GameFactory.GRID,
                y: y * GameFactory.GRID,
                targetY: targetY * GameFactory.GRID,
                ...rest,
            }),
        exit: ({ id, x, y, w = 80, h = 112, ...rest } = {}) =>
            GameFactory.exit({
                id,
                x: x * GameFactory.GRID,
                y: y * GameFactory.GRID,
                w,
                h,
                ...rest,
            }),
        message: ({
            id,
            x,
            y,
            w,
            h,
            offsetX = 0,
            offsetY = 0,
            lines,
            relatedTo,
            strategy,
            displayTime,
        } = {}) =>
            GameFactory.message({
                id,
                x: x * GameFactory.GRID,
                y: y * GameFactory.GRID,
                w: w * GameFactory.GRID,
                h: h * GameFactory.GRID,
                offsetX: offsetX * GameFactory.GRID,
                offsetY: offsetY * GameFactory.GRID,
                lines,
                relatedTo,
                strategy,
                displayTime,
            }),
        solid: ({ id, x, y, w, h, layout = "ground" } = {}) =>
            GameFactory.solid({
                id,
                x: x * GameFactory.GRID,
                y: y * GameFactory.GRID,
                w: w * GameFactory.GRID,
                h: h * GameFactory.GRID,
                layout,
            }),
        oneDirection: ({ id, x, y, w, h, layout = "boardOneDirection" } = {}) =>
            GameFactory.oneDirection({
                id,
                x: x * GameFactory.GRID,
                y: y * GameFactory.GRID,
                w: w * GameFactory.GRID,
                h: h * GameFactory.GRID,
                layout,
            }),
        cracks: ({ id, x, y, w, h, layout = "cracks" } = {}) =>
            GameFactory.cracks({
                id,
                x: x * GameFactory.GRID,
                y: y * GameFactory.GRID,
                w: w * GameFactory.GRID,
                h: h * GameFactory.GRID,
                layout,
            }),
        booster: ({ id, x, y, w, h, boostSpeed = 20 } = {}) =>
            GameFactory.booster({
                id,
                x: x * GameFactory.GRID,
                y: y * GameFactory.GRID,
                w: w * GameFactory.GRID,
                h: h * GameFactory.GRID,
                boostSpeed,
            }),
        elevator: ({
            id,
            startX,
            startY,
            w,
            h,
            targetX,
            targetY,
            speed,
            waitTime,
            layout,
            triggered,
        } = {}) =>
            GameFactory.elevator({
                id,
                startX: startX * GameFactory.GRID,
                startY: startY * GameFactory.GRID,
                w: w * GameFactory.GRID,
                h: h * GameFactory.GRID,
                targetX: targetX * GameFactory.GRID,
                targetY: targetY * GameFactory.GRID,
                speed,
                waitTime,
                layout,
                triggered,
            }),
        coins: ({ id, x, y, ...rest } = {}) =>
            GameFactory.collectible({
                id,
                x: x * GameFactory.GRID + GameFactory.GRID / 4,
                y: y * GameFactory.GRID + GameFactory.GRID / 4,
                ...rest,
            }),
        hearts: ({ id, x, y, ...rest } = {}) =>
            GameFactory.collectible({
                id,
                x: x * GameFactory.GRID + GameFactory.GRID / 4,
                y: y * GameFactory.GRID + GameFactory.GRID / 4,
                ...rest,
            }),
        splinters: ({ id, x, y, ...rest } = {}) =>
            GameFactory.collectible({
                id,
                x: x * GameFactory.GRID,
                y: y * GameFactory.GRID,
                w: 50,
                h: 50,
                ...rest,
            }),
        rowOfCollectibles: ({ startId, count, x, y, gap = 1 } = {}) =>
            GameFactory.rowOfCollectibles({
                startId,
                count,
                startX: x * GameFactory.GRID + GameFactory.GRID / 4,
                y: y * GameFactory.GRID + GameFactory.GRID / 4,
                gap: gap * GameFactory.GRID,
            }),
        columnOfCollectibles: ({ startId, count, x, y, gap = 1 } = {}) =>
            GameFactory.columnOfCollectibles({
                startId,
                count,
                x: x * GameFactory.GRID + GameFactory.GRID / 4,
                startY: y * GameFactory.GRID + GameFactory.GRID / 4,
                gap: gap * GameFactory.GRID,
            }),
        rowOfSpikes: ({
            startId,
            count,
            x,
            y,
            position = "down",
            damage = 1,
        } = {}) =>
            GameFactory.rowOfSpikes({
                startId,
                count,
                startX: x * GameFactory.GRID,
                y: y * GameFactory.GRID,
                position,
                damage,
            }),
        spike: ({
            id,
            x,
            y,
            variant = 1,
            position = "down",
            damage = 1,
        } = {}) =>
            GameFactory.spike({
                id,
                x: x * GameFactory.GRID,
                y: y * GameFactory.GRID,
                variant,
                position,
                damage,
            }),
        checkpoint: ({
            id,
            x,
            y,
            w,
            h,
            reached = false,
            message = {},
        } = {}) => {
            const cp = {
                ...GameFactory.environment.checkpoint({
                    id,
                    x: x * GameFactory.GRID,
                    y: y * GameFactory.GRID,
                    w: w * GameFactory.GRID,
                    h: h * GameFactory.GRID,
                    reached,
                }),
                back: GameFactory.environment.checkpointBack({
                    x: x * GameFactory.GRID - 6 * GameFactory.SCALE,
                    y: y * GameFactory.GRID,
                }),
                front: GameFactory.environment.checkpointFront({
                    x: x * GameFactory.GRID,
                    y: y * GameFactory.GRID,
                }),
                platform: {
                    id: _nextCheckpointPlatformId++,
                    x: x * GameFactory.GRID,
                    y: y * GameFactory.GRID,
                    w: 30,
                    h: 3,
                    type: "solid",
                    layout: "simple",
                    color: "#bd067b",
                },
            };
            if (message !== undefined) {
                const {
                    offsetX = 0,
                    offsetY = -2,
                    lines = MESSAGES.CHECKPOINT,
                    relatedTo = "hitBox",
                    strategy = "single",
                    displayTime = 3000,
                } = message;
                cp.message = GameFactory.message({
                    id: `checkpoint-${id}-msg`,
                    x: x * GameFactory.GRID,
                    y: y * GameFactory.GRID,
                    w: w * GameFactory.GRID,
                    h: h * GameFactory.GRID,
                    offsetX: offsetX * GameFactory.GRID,
                    offsetY: offsetY * GameFactory.GRID,
                    lines,
                    relatedTo,
                    strategy,
                    displayTime,
                });
            }
            return cp;
        },
        environment: {
            checkpointBack: ({ x, y, ...rest } = {}) =>
                GameFactory.environment.checkpointBack({
                    x: x * GameFactory.GRID - 6 * GameFactory.SCALE,
                    y: y * GameFactory.GRID,
                    ...rest,
                }),
            checkpointFront: ({ x, y, ...rest } = {}) =>
                GameFactory.environment.checkpointFront({
                    x: x * GameFactory.GRID,
                    y: y * GameFactory.GRID,
                    ...rest,
                }),
            plant001: ({ x, y, ...rest } = {}) =>
                GameFactory.environment.plant001({
                    x: x * GameFactory.GRID,
                    y: y * GameFactory.GRID - 14 * GameFactory.SCALE,
                    ...rest,
                }),
            plant002: ({ x, y, ...rest } = {}) =>
                GameFactory.environment.plant002({
                    x: x * GameFactory.GRID,
                    y: y * GameFactory.GRID - 12 * GameFactory.SCALE,
                    ...rest,
                }),
            plant003: ({ x, y, ...rest } = {}) =>
                GameFactory.environment.plant003({
                    x: x * GameFactory.GRID,
                    y: y * GameFactory.GRID - 7 * GameFactory.SCALE,
                    ...rest,
                }),
            plant004: ({ x, y, ...rest } = {}) =>
                GameFactory.environment.plant004({
                    x: x * GameFactory.GRID,
                    y: y * GameFactory.GRID - 8 * GameFactory.SCALE,
                    ...rest,
                }),
            plant005: ({ x, y, ...rest } = {}) =>
                GameFactory.environment.plant005({
                    x: x * GameFactory.GRID + 2 * GameFactory.SCALE,
                    y: y * GameFactory.GRID,
                    ...rest,
                }),
            plant006: ({ x, y, ...rest } = {}) =>
                GameFactory.environment.plant006({
                    x: x * GameFactory.GRID - 2 * GameFactory.SCALE,
                    y: y * GameFactory.GRID,
                    ...rest,
                }),
            wallPlant001: ({ x, y, ...rest } = {}) =>
                GameFactory.environment.wallPlant001({
                    x: x * GameFactory.GRID,
                    y: y * GameFactory.GRID,
                    ...rest,
                }),
            plate001: ({ x, y, ...rest } = {}) =>
                GameFactory.environment.plate001({
                    x: x * GameFactory.GRID,
                    y: y * GameFactory.GRID - 7 * GameFactory.SCALE,
                    ...rest,
                }),
            flower001: ({ x, y, ...rest } = {}) =>
                GameFactory.environment.flower001({
                    x: x * GameFactory.GRID,
                    y: y * GameFactory.GRID - 14 * GameFactory.SCALE,
                    ...rest,
                }),
            flower002: ({ x, y, ...rest } = {}) =>
                GameFactory.environment.flower002({
                    x: x * GameFactory.GRID,
                    y: y * GameFactory.GRID - 14 * GameFactory.SCALE,
                    ...rest,
                }),
            elevatorPanel: ({ x, y, ...rest } = {}) =>
                GameFactory.environment.elevatorPanel({
                    x: x * GameFactory.GRID,
                    y: y * GameFactory.GRID - 16 * GameFactory.SCALE,
                    ...rest,
                }),
            wallClean: ({ x, y, w = 1, h = 1, ...rest } = {}) =>
                GameFactory.environment.wallClean({
                    x: x * GameFactory.GRID,
                    y: y * GameFactory.GRID,
                    w: (w * GameFactory.GRID) / GameFactory.SCALE,
                    h: (h * GameFactory.GRID) / GameFactory.SCALE,
                    ...rest,
                }),
            wallSharpLeftTop: ({ x, y, ...rest } = {}) =>
                GameFactory.environment.wallSharpLeftTop({
                    x: x * GameFactory.GRID,
                    y: y * GameFactory.GRID,
                    ...rest,
                }),
            wallSharpLeft: ({ x, y, ...rest } = {}) =>
                GameFactory.environment.wallSharpLeft({
                    x: x * GameFactory.GRID,
                    y: y * GameFactory.GRID,
                    ...rest,
                }),
            wallSharpLeftBottom: ({ x, y, ...rest } = {}) =>
                GameFactory.environment.wallSharpLeftBottom({
                    x: x * GameFactory.GRID,
                    y: y * GameFactory.GRID,
                    ...rest,
                }),
            wallSharpLeftCol: ({ x, y, count, ...rest } = {}) =>
                GameFactory.environment.wallSharpLeftCol({
                    x: x * GameFactory.GRID,
                    y: y * GameFactory.GRID,
                    count,
                    ...rest,
                }),
            wallSharpRightTop: ({ x, y, ...rest } = {}) =>
                GameFactory.environment.wallSharpRightTop({
                    x: x * GameFactory.GRID,
                    y: y * GameFactory.GRID,
                    ...rest,
                }),
            wallSharpRight: ({ x, y, ...rest } = {}) =>
                GameFactory.environment.wallSharpRight({
                    x: x * GameFactory.GRID,
                    y: y * GameFactory.GRID,
                    ...rest,
                }),
            wallSharpRightBottom: ({ x, y, ...rest } = {}) =>
                GameFactory.environment.wallSharpRightBottom({
                    x: x * GameFactory.GRID,
                    y: y * GameFactory.GRID,
                    ...rest,
                }),
            wallSharpRightCol: ({ x, y, count, ...rest } = {}) =>
                GameFactory.environment.wallSharpRightCol({
                    x: x * GameFactory.GRID,
                    y: y * GameFactory.GRID,
                    count,
                    ...rest,
                }),
            wallSharpHole: ({ x, y, ...rest } = {}) =>
                GameFactory.environment.wallSharpHole({
                    x: x * GameFactory.GRID,
                    y: y * GameFactory.GRID,
                    ...rest,
                }),
            wallInside: ({ x, y, ...rest } = {}) =>
                GameFactory.environment.wallInside({
                    x: x * GameFactory.GRID,
                    y: y * GameFactory.GRID,
                    ...rest,
                }),
        },
    },
};
