export const GameFactory = {
    GRID: 48,
    SCALE: 3,
    player: (overrides = {}) => ({
        x: 0,
        y: 0,
        prevX: 0,
        prevY: 0,
        w: 36,
        h: 107,
        vx: 0,
        vy: 0,
        life: 6,
        maxLife: 6,
        isHit: false,
        lastHitTime: 0,
        hitCooldown: 1000,
        acceleration: 0.8,
        deceleration: 1.2,
        airAcceleration: 2,
        airDeceleration: 2,
        speed: 5.8,
        crouchSpeed: 4,
        crouchHeight: 45,
        crouchWidth: 72,
        originalHeight: 107,
        originalWidth: 36,
        airborne: true,
        jump: 16.4,
        jumpPressedByUser: false,
        jumpPressedAt: 0,
        jumpBufferDuration: 80,
        lastGroundedAt: 0,
        coyoteDuration: 80,
        onGroundId: null,
        onGroundType: null,
        lastGroundId: null,
        lastGroundType: null,
        coinsCount: 0,
        splintersCount: 0,
        facing: "right",
        shooting: false,
        lastShootTime: 0,
        shootingOffsetY: -4,
        shootingCrouchOffsetY: 4,
        shootingOffsetX: 40,
        shootingCrouchOffsetX: 44,
        ...overrides,
    }),
    solid: (id, x, y, w, h, layout = "ground") => ({
        id,
        x,
        y,
        w,
        h,
        type: "solid",
        layout,
    }),
    booster: (id, x, y, w, h, boostSpeed = 20) => ({
        id,
        x,
        y,
        w,
        h,
        elasticity: 0,
        type: "booster",
        layout: "booster",
        boostSpeed,
    }),
    elevator: (
        id,
        startX,
        startY,
        w,
        h,
        targetX,
        targetY,
        speed,
        waitTime,
        layout = "brick",
    ) => {
        const dx = targetX - startX;
        const dy = targetY - startY;

        const length = Math.hypot(dx, dy);

        return {
            id,
            x: startX,
            y: startY,
            w,
            h,

            startX,
            startY,
            targetX,
            targetY,

            dirX: dx / length,
            dirY: dy / length,

            speed,
            direction: 1,

            waitTime,
            idleUntil: 0,

            type: "elevator",
            layout,
        };
    },
    enemy: (id, minX, maxX, y, speed = 1.5, overrides = {}) => ({
        id,
        minX,
        maxX,
        x: minX,
        y,
        w: 36,
        h: 84,
        speed,
        vx: speed,
        health: 15,
        recoilX: 18,
        recoilY: 6,
        isDamaged: false,
        damage: 1,
        damageTime: 0,
        type: "pill",
        mainColor: "#e84855", // vivid coral red
        secondaryColor: "#f7b32b", // warm amber yellow
        ...overrides,
    }),
    scissors: (id, minX, maxX, y, speed = 1.5, overrides = {}) => ({
        id,
        minX,
        maxX,
        x: minX,
        y,
        w: 16 * 3,
        h: 16 * 3,
        speed,
        vx: speed,
        health: 10,
        recoilX: 12,
        recoilY: 6,
        isDamaged: false,
        damage: 1,
        damageTime: 0,
        type: "scissors",
        ...overrides,
    }),
    collectible: (id, x, y, overrides = {}) => ({
        id,
        x,
        y,
        w: 24,
        h: 24,
        collected: false,
        ...overrides,
    }),
    weapon: (overrides = {}) => ({
        id: null,
        color: "#ffc300",
        speed: 12,
        shootFrequency: 125,
        ammo: {
            vx: 0,
            vy: 0,
            w: 8,
            h: 8,
            damage: 5,
        },
        ...overrides,
    }),
    rowOfCollectibles: (startId, count, startX, y, gap) =>
        Array.from({ length: count }, (_, i) =>
            GameFactory.collectible(startId + i, startX + i * gap, y),
        ),
    columnOfCollectibles: (startId, count, x, startY, gap) =>
        Array.from({ length: count }, (_, i) =>
            GameFactory.collectible(startId + i, x, startY + i * gap),
        ),
    rowOfSpikes: (startId, count, startX, y, damage = 1) => {
        const spikeW = 16 * GameFactory.SCALE;
        return Array.from({ length: count }, (_, i) =>
            GameFactory.spike(
                startId + i,
                startX + i * spikeW,
                y,
                undefined,
                undefined,
                damage,
                (i % 2) + 1,
            ),
        );
    },
    spike: (
        id,
        x,
        y,
        w = 16 * GameFactory.SCALE,
        h = 16 * GameFactory.SCALE,
        damage = 1,
        variant = 1,
        recoilX = 9,
        recoilY = 9,
    ) => ({
        id,
        x,
        y,
        w,
        h,
        damage,
        variant,
        recoilX,
        recoilY,
        type: "spike",
    }),
    environment: {
        plant001: (x, y, overrides = {}) => ({
            x,
            y,
            url: "textures/tilesets.png",
            cordX: 48,
            cordY: 98,
            w: 32,
            h: 30,
            ...overrides,
        }),
        plant002: (x, y, overrides = {}) => ({
            x,
            y,
            url: "textures/tilesets.png",
            cordX: 16,
            cordY: 100,
            w: 32,
            h: 32,
            ...overrides,
        }),
        plant003: (x, y, overrides = {}) => ({
            x,
            y,
            url: "textures/tilesets.png",
            cordX: 96,
            cordY: 105,
            w: 16,
            h: 21,
            ...overrides,
        }),
        plant004: (x, y, overrides = {}) => ({
            x,
            y,
            url: "textures/tilesets.png",
            cordX: 128,
            cordY: 104,
            w: 16,
            h: 22,
            ...overrides,
        }),
        wallPlant001: (x, y, overrides = {}) => ({
            x,
            y,
            url: "textures/tilesets.png",
            cordX: 128,
            cordY: 48,
            w: 16,
            h: 27,
            ...overrides,
        }),
        plate001: (x, y, overrides = {}) => ({
            x,
            y,
            url: "textures/tilesets.png",
            cordX: 160,
            cordY: 107,
            w: 32,
            h: 21,
            ...overrides,
        }),
        flower001: (x, y, overrides = {}) => ({
            x,
            y,
            url: "textures/props.png",
            cordX: 45,
            cordY: 16,
            w: 32,
            h: 46,
            ...overrides,
        }),
        flower002: (x, y, overrides = {}) => ({
            x,
            y,
            url: "textures/props.png",
            cordX: 4,
            cordY: 32,
            w: 32,
            h: 32,
            ...overrides,
        }),
        elevatorPanel: (x, y, overrides = {}) => ({
            x,
            y,
            url: "textures/tilesets-2.png",
            cordX: 16,
            cordY: 0,
            w: 32,
            h: 80,
            ...overrides,
        }),
    },
    grid: {
        enemy: (id, minX, maxX, y, speed, overrides = {}) =>
            GameFactory.enemy(
                id,
                minX * GameFactory.GRID,
                maxX * GameFactory.GRID,
                y * GameFactory.GRID + 4 * GameFactory.SCALE,
                speed,
                overrides,
            ),
        scissors: (id, minX, maxX, y, speed, overrides = {}) =>
            GameFactory.scissors(
                id,
                minX * GameFactory.GRID,
                maxX * GameFactory.GRID,
                y * GameFactory.GRID,
                speed,
                overrides,
            ),
        solid: (id, gx, gy, gw, gh, layout = "ground") =>
            GameFactory.solid(
                id,
                gx * GameFactory.GRID,
                gy * GameFactory.GRID,
                gw * GameFactory.GRID,
                gh * GameFactory.GRID,
                layout,
            ),
        booster: (id, gx, gy, gw, gh, boostSpeed = 20) =>
            GameFactory.booster(
                id,
                gx * GameFactory.GRID,
                gy * GameFactory.GRID,
                gw * GameFactory.GRID,
                gh * GameFactory.GRID,
                boostSpeed,
            ),
        elevator: (
            id,
            startGX,
            startGY,
            gw,
            gh,
            targetGX,
            targetGY,
            speed,
            waitTime,
            layout,
        ) =>
            GameFactory.elevator(
                id,
                startGX * GameFactory.GRID,
                startGY * GameFactory.GRID,
                gw * GameFactory.GRID,
                gh * GameFactory.GRID,
                targetGX * GameFactory.GRID,
                targetGY * GameFactory.GRID,
                speed,
                waitTime,
                layout,
            ),

        coins: (id, gx, gy, overrides = {}) =>
            GameFactory.collectible(
                id,
                gx * GameFactory.GRID + GameFactory.GRID / 4,
                gy * GameFactory.GRID + GameFactory.GRID / 4,
                overrides,
            ),
        hearts: (id, gx, gy, overrides = {}) =>
            GameFactory.collectible(
                id,
                gx * GameFactory.GRID + GameFactory.GRID / 4,
                gy * GameFactory.GRID + GameFactory.GRID / 4,
                overrides,
            ),
        splinters: (id, gx, gy, overrides = {}) =>
            GameFactory.collectible(
                id,
                gx * GameFactory.GRID,
                gy * GameFactory.GRID,
                {
                    w: 50,
                    h: 50,
                    ...overrides,
                },
            ),
        rowOfCollectibles: (startId, count, gStartX, gy, gGap) =>
            GameFactory.rowOfCollectibles(
                startId,
                count,
                gStartX * GameFactory.GRID + GameFactory.GRID / 4,
                gy * GameFactory.GRID + GameFactory.GRID / 4,
                gGap * GameFactory.GRID,
            ),
        columnOfCollectibles: (startId, count, gx, gStartY, gGap) =>
            GameFactory.columnOfCollectibles(
                startId,
                count,
                gx * GameFactory.GRID + GameFactory.GRID / 4,
                gStartY * GameFactory.GRID + GameFactory.GRID / 4,
                gGap * GameFactory.GRID,
            ),
        rowOfSpikes: (startId, count, gStartX, gy, damage = 1) =>
            GameFactory.rowOfSpikes(
                startId,
                count,
                gStartX * GameFactory.GRID,
                gy * GameFactory.GRID,
                damage,
            ),
        spike: (id, gx, gy, variant = 1, damage = 1) =>
            GameFactory.spike(
                id,
                gx * GameFactory.GRID,
                gy * GameFactory.GRID,
                16 * GameFactory.SCALE,
                16 * GameFactory.SCALE,
                damage,
                variant,
            ),
        environment: {
            plant001: (gx, gy, overrides = {}) =>
                GameFactory.environment.plant001(
                    gx * GameFactory.GRID,
                    gy * GameFactory.GRID - 14 * GameFactory.SCALE,
                    overrides,
                ),
            plant002: (gx, gy, overrides = {}) =>
                GameFactory.environment.plant002(
                    gx * GameFactory.GRID,
                    gy * GameFactory.GRID - 12 * GameFactory.SCALE,
                    overrides,
                ),
            plant003: (gx, gy, overrides = {}) =>
                GameFactory.environment.plant003(
                    gx * GameFactory.GRID,
                    gy * GameFactory.GRID - 7 * GameFactory.SCALE,
                    overrides,
                ),
            plant004: (gx, gy, overrides = {}) =>
                GameFactory.environment.plant004(
                    gx * GameFactory.GRID,
                    gy * GameFactory.GRID - 8 * GameFactory.SCALE,
                    overrides,
                ),
            wallPlant001: (gx, gy, overrides = {}) =>
                GameFactory.environment.wallPlant001(
                    gx * GameFactory.GRID,
                    gy * GameFactory.GRID,
                    overrides,
                ),
            plate001: (gx, gy, overrides = {}) =>
                GameFactory.environment.plate001(
                    gx * GameFactory.GRID,
                    gy * GameFactory.GRID - 7 * GameFactory.SCALE,
                    overrides,
                ),
            flower001: (gx, gy, overrides = {}) =>
                GameFactory.environment.flower001(
                    gx * GameFactory.GRID,
                    gy * GameFactory.GRID - 14 * GameFactory.SCALE,
                    overrides,
                ),
            flower002: (gx, gy, overrides = {}) =>
                GameFactory.environment.flower002(
                    gx * GameFactory.GRID,
                    gy * GameFactory.GRID - 14 * GameFactory.SCALE,
                    overrides,
                ),
            elevatorPanel: (gx, gy, overrides = {}) =>
                GameFactory.environment.elevatorPanel(
                    gx * GameFactory.GRID,
                    gy * GameFactory.GRID - 16 * GameFactory.SCALE,
                    overrides,
                ),
        },
    },
};
